version: "3"

tasks:
  default:
    silent: true
    desc: 実行可能なすべてのタスクを表示
    cmds:
      - task --list-all

  local-up:
    desc: ローカル環境のセットアップ(主にコンテナ起動)
    cmds:
      - docker compose -f ./local-setup/docker-compose.yaml up -d

  local-down:
    desc: ローカル環境の停止(主にコンテナ停止)
    cmds:
      - docker compose -f ./local-setup/docker-compose.yaml down

  atlas-migrate-diff:
    desc: データベースのマイグレーション差分を生成
    dir: ./database
    cmds:
      - atlas migrate diff --dev-url "docker://mysql/8/dev" --dir "file://migrations" --to "file://schema.mysql.sql"

  atlas-migrate-apply:
    desc: データベースのマイグレーションを適用
    dir: ./database
    deps:
      - local-up
    cmds:
     # TODO:MYSQLが立ち上がっているかの確認をしないといけない。
      - atlas migrate apply --url "mysql://root:passw0rd@localhost:3306/inaba" --dir "file://migrations"