spring:
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    jp.inaba: DEBUG

aws:
  cognito:
    endpoint: http://localhost:5050

axoniq:
  console:
    application-name: ${APPLICATION_NAME}
    credentials: ${AXONIQ_CONSOLE_CREDENTIALS}
    dlq-mode: FULL