server:
  port: ${SERVER_PORT:8083}

grpc:
  server:
    port: ${GRPC_PORT:8183}

spring:
  application:
    name: inaba-service

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson

aws:
  cognito:
    user-pool-id: ${AWS_COGNITO_USER-POOL-ID}
    client-id: ${AWS_COGNITO_CLIENT-ID}