spring:
  profiles:
    active: local
    group:
      local:
        - app-common
        - app-local
        - axon-server
        - datastore-mysql
      local-with-axoniq:
        - app-common
        - app-local-with-axoniq
        - axon-server
        - datastore-mysql
      test:
        - app-common
        - app-test
        - axon-server
        - datastore-mysql
      prod:
        - app-common
        - app-prod
        - axon-server
        - datastore-mysql