server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: inaba-service

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson

aws:
  cognito:
    client-id: ${AWS_COGNITO_CLIENT-ID}