spring:
  # docker-composeをupするタイミングはこちらで制御したいのでoffに
  docker-compose-enabled: false
  profiles:
    active: local
    group:
      integration-test:
        - app-integration-test
      local:
        - app-common
        - app-local
        - axon-server
        - datastore-mysql
      local-with-axoniq:
        - app-common
        - app-local
        - axon-server
        - axoniq-console
        - datastore-mysql
      test:
        - app-common
        - app-test
        - axon-server
        - axoniq-console
        - datastore-mysql
      prod:
        - app-common
        - app-prod
        - axon-server
        - axoniq-console
        - datastore-mysql
