spring:
  profiles:
    active: local
    group:
      local:
        - app-common
        - app-local
      test:
        - app-common
        - app-test
      prod:
        - app-common
        - app-prod