spring:
  profiles:
    active: local
    group:
      local:
        - app-common
        - app-local
        - security-oidc
      test:
        - app-common
        - app-test
        - security-oidc
      prod:
        - app-common
        - app-prod
        - security-oidc