services:
  axon-server:
    image: axoniq/axonserver:latest
    container_name: axon-server
    healthcheck:
      test: curl -f http://localhost:8024/actuator/health || exit 1;
    ports:
      - 8024:8024
      - 8124:8124

  # 本来であればサービスごとにDBを立てるがlocal環境なのでまとめる
  common-datastore:
    image: mysql:latest
    container_name: common-datastore
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd

  cognito:
    image: jagregory/cognito-local:latest
    container_name: cognito
    ports:
      - 9229:9229

  kms:
    image: nsmithuk/local-kms:latest
    container_name: kms
    ports:
      - 8080:8080