services:
  # AxonServer
  axon-server:
    image: axoniq/axonserver:latest
    environment:
      # 初期設定(Context作成)をしなくてもよくなる
      - 'AXONIQ_AXONSERVER_STANDALONE=TRUE'
    healthcheck:
      test: curl -f http://localhost:8024/actuator/health || exit 1;
    volumes:
      - axonserver-data:/axonserver/data
      - axonserver-events:/axonserver/events
      - axonserver-log:/axonserver/log
    ports:
      - 8024:8024
      - 8124:8124
      - 8224:8224

  # 本当だったらサービスごとにDB作るけど、今はまとめる。
  common-datastore:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
    volumes:
      - mysql-store:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  axonserver-data:
  axonserver-events:
  axonserver-log:
  mysql-store: